apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-blue-0
  namespace: kube-ops
spec:
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins-home-jenkins-blue-0
    namespace: kube-ops
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.46
    path: "/export/k8s/jenkins-blue"
